[tools.piter]
env_root = "my_envs"
dependencies = [
    "typer ==0.4.0",
    "colorama ==0.4.4"
]

[tools.piter.env.dev]
dependencies = [
    "black==19.10b0"
]
scripts.lint = "black piter"

[tools.piter.env.test]
dependencies = [
    "pytest==6.2.5",
    "coverage[toml]==6.2"
]

scripts.install = "pip install --editable ."
scripts.test = [
    "coverage run -m pytest",
    "coverage report"
]

vars.TEST_ENV_VAR = "TEST_VALUE"
vars.TEST_ENV_VAR_2 = "TEST_VALUE_2"

[tools.piter.env.ci]
dependencies = [
    "pytest==6.2.5",
    "coverage[toml]==6.2"
]

scripts.test = [
    "pip install --editable .",
    "coverage run -m pytest",
    "coverage xml"
]

[tool.coverage.run]
source = ["piter"]
